import {
  Search, Plus, Star, Calendar, Trash2, Edit3,
  Film, User, Heart, ChevronLeft, ChevronRight, Filter, Menu, X, Check,
  Tv, Clapperboard, Upload, ExternalLink, ListVideo, Image,
  CloudUpload, CloudOff, CheckCircle, XCircle, Loader2,
  LogIn, LogOut, Mail, Lock, RefreshCw, Download, Settings, Shuffle
} from 'lucide-react';

export const Icons = {
  Search,
  Plus,
  Star,
  Calendar,
  Trash: Trash2,
  Edit: Edit3,
  Film,
  Tv,
  Clapperboard,
  User,
  Heart,
  Back: ChevronLeft,
  ChevronRight,
  Filter,
  Menu,
  Close: X,
  Check,
  Upload,
  ExternalLink,
  ListVideo,
  Image,
  CloudUpload,
  CloudOff,
  CheckCircle,
  XCircle,
  Loading: Loader2,
  LogIn,
  LogOut,
  Mail,
  Lock,
  RefreshCw,
  Download,
  Settings,
  Shuffle,
};